version: "3.2"
services:
  app:
    build:
      context: .
    container_name: myscraper
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=dev
    ports:
      - 5432:5432
